language: objective-c
cache: bundle

before_script:
  - script/ci/travis/instruments-auth.sh

script:
  - script/ci/travis/bundle-install.rb
  - script/ci/travis/build-and-stage-app.sh
  - script/ci/travis/cucumber-ci.rb --tags ~@no_ci --tags ~@scroll

notifications:
  email:
    on_success: change
    on_failure: always
