language: objective-c
cache: bundle

before_script:
  - gem install luffa --no-document --env-shebang --no-prerelease
  - luffa authorize

script:
  - script/ci/travis/bundle-install.rb
  - script/ci/travis/build-and-stage-app.sh
  - script/ci/travis/cucumber-ci.rb --tags @travis

notifications:
  email:
    on_success: change
    on_failure: always
